import type { User, Project } from '../types';

export const mockUsers: User[] = [
  {
    id: 1,
    username: 'admin',
    password: 'admin123',
    realName: '管理员',
    department: '系统管理',
    phone: '13800000001',
    email: 'admin@company.com',
    status: '启用',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 2,
    username: 'zhangsan',
    password: '123456',
    realName: '张三',
    department: '开发部门',
    phone: '13900000002',
    email: 'zhangsan@company.com',
    status: '启用',
    createdAt: new Date('2025-03-15'),
    updatedAt: new Date('2025-06-20'),
  },
  {
    id: 3,
    username: 'lisi',
    password: '123456',
    realName: '李四',
    department: '储能部门',
    phone: '13700000003',
    status: '禁用',
    createdAt: new Date('2025-04-10'),
    updatedAt: new Date('2025-07-01'),
  },
  {
    id: 4,
    username: 'wangwu',
    password: '123456',
    realName: '王五',
    department: '智慧部门',
    phone: '13600000004',
    email: 'wangwu@company.com',
    status: '启用',
    createdAt: new Date('2025-05-01'),
    updatedAt: new Date('2025-05-01'),
  },
];

export const mockProjects: Project[] = [
  {
    id: 1,
    name: '苏州3MW光伏项目',
    capacity: 3,
    investmentType: '并购',
    status: '正常',
    department: '开发部门',
    manager: '张三',
    subManager: '',
    currentNode: '资料交接',
    nodeStatus: '进行中',
    overdueDays: 10,
    totalProgress: 0.10,
    remark: '苏州地区3MW光伏发电项目，预计年发电量300万度',
    nodes: [
      { id: 1, nodeName: '立项', plannedStart: null, plannedEnd: null, actualComplete: null, supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 2, nodeName: '投决', plannedStart: '2025-12-29', plannedEnd: '2025-12-29', actualComplete: '2025-12-29', supportMaterial: '上传PDF/截图', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 3, nodeName: '并网', plannedStart: '2025-12-30', plannedEnd: '2025-12-30', actualComplete: '2025-12-30', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 4, nodeName: '合同签署', plannedStart: '2025-12-31', plannedEnd: '2025-12-31', actualComplete: '2025-12-31', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 5, nodeName: '付款', plannedStart: '2025-12-31', plannedEnd: '2025-12-31', actualComplete: '2025-12-31', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 6, nodeName: '工商', plannedStart: '2025-12-30', plannedEnd: '2025-12-30', actualComplete: '2025-12-30', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 7, nodeName: '资料交接', plannedStart: '2025-12-31', plannedEnd: '2026-01-13', actualComplete: null, supportMaterial: '', progressStatus: '进行中', overdueDays: 97, tab: '前期', group: '项目端' },
      { id: 8, nodeName: '消缺', plannedStart: '2025-12-31', plannedEnd: '2026-04-30', actualComplete: null, supportMaterial: '', progressStatus: '未开始', overdueDays: -10, tab: '前期', group: '项目端' },
    ],
    createdAt: new Date('2025-12-01'),
  },
  {
    id: 2,
    name: '石家庄EC风机改造项目（一期）',
    capacity: null,
    investmentType: '合资',
    status: '正常',
    department: '智慧公司',
    manager: '李四',
    subManager: 'XX',
    currentNode: '合同签署/工商登记',
    nodeStatus: '进行中',
    overdueDays: 8,
    totalProgress: 0.70,
    nodes: [
      { id: 1, nodeName: '立项', plannedStart: null, plannedEnd: null, actualComplete: null, supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 2, nodeName: '投决', plannedStart: '2025-12-17', plannedEnd: '2025-12-17', actualComplete: '2025-12-17', supportMaterial: '投决流程', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 3, nodeName: '合同签署/工商登记', plannedStart: '2025-12-17', plannedEnd: '2025-12-31', actualComplete: null, supportMaterial: '', progressStatus: '进行中', overdueDays: 110, tab: '前期', group: '项目端', remark: '预计3月份完成签约' },
      { id: 4, nodeName: '开工建设-竣工验收', plannedStart: '2026-03-01', plannedEnd: '2026-05-01', actualComplete: null, supportMaterial: '', progressStatus: '未开始', overdueDays: -11, tab: '建设期', group: '项目端' },
    ],
    createdAt: new Date('2025-10-01'),
  },
  {
    id: 3,
    name: '广东8MW/16MWh电化学储能项目',
    capacity: 8,
    investmentType: '自投',
    status: '正常',
    department: '储能事业部',
    manager: '王五',
    subManager: '',
    currentNode: '立项',
    nodeStatus: '进行中',
    overdueDays: 0,
    totalProgress: 0.05,
    nodes: [
      { id: 1, nodeName: '前期开发', plannedStart: '2025-10-01', plannedEnd: '2025-10-01', actualComplete: '2025-09-01', supportMaterial: '', progressStatus: '已完成', overdueDays: -30, tab: '前期', group: '项目端' },
      { id: 2, nodeName: '立项', plannedStart: '2026-01-28', plannedEnd: '2026-01-28', actualComplete: '2026-01-28', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 3, nodeName: '投决', plannedStart: '2026-03-01', plannedEnd: '2026-04-01', actualComplete: null, supportMaterial: '', progressStatus: '进行中', overdueDays: 19, tab: '前期', group: '项目端' },
      { id: 4, nodeName: '合同签署/工商登记', plannedStart: '2026-04-01', plannedEnd: null, actualComplete: null, supportMaterial: '', progressStatus: '未开始', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 5, nodeName: '开工建设-竣工验收', plannedStart: '2026-04-15', plannedEnd: null, actualComplete: null, supportMaterial: '', progressStatus: '未开始', overdueDays: 0, tab: '建设期', group: '项目端' },
    ],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 4,
    name: '山西200MW/400MWH项目',
    capacity: 200,
    investmentType: '自投',
    status: '正常',
    department: '战略客户部',
    manager: '赵六',
    subManager: '',
    currentNode: '立项会',
    nodeStatus: '已完成',
    overdueDays: 7,
    totalProgress: 0.05,
    nodes: [
      { id: 1, nodeName: '前期开发', plannedStart: '2026-02-11', plannedEnd: '2026-03-02', actualComplete: '2026-03-02', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 2, nodeName: '投决', plannedStart: '2026-03-03', plannedEnd: '2026-03-03', actualComplete: '2026-03-03', supportMaterial: '', progressStatus: '已完成', overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 3, nodeName: '立项会', plannedStart: '2026-03-25', plannedEnd: '2026-03-25', actualComplete: '2026-03-28', supportMaterial: '', progressStatus: '已完成', overdueDays: 3, tab: '前期', group: '项目端' },
    ],
    createdAt: new Date('2026-03-01'),
  },
  {
    id: 5,
    name: '江苏分布式光伏项目',
    capacity: 5,
    investmentType: '自投',
    status: '正常',
    department: '开发部门',
    manager: '张三',
    currentNode: '建设',
    nodeStatus: '进行中',
    overdueDays: 0,
    totalProgress: 0.85,
    nodes: [
      { id: 1, nodeName: '前期开发', plannedStart: null, plannedEnd: null, actualComplete: new Date('2025-11-01'), overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 2, nodeName: '立项', plannedStart: new Date('2025-11-15'), plannedEnd: new Date('2025-11-30'), actualComplete: new Date('2025-11-30'), overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 3, nodeName: '投决', plannedStart: new Date('2025-12-01'), plannedEnd: new Date('2025-12-15'), actualComplete: new Date('2025-12-15'), overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 4, nodeName: '合同签署', plannedStart: new Date('2025-12-16'), plannedEnd: new Date('2025-12-31'), actualComplete: new Date('2025-12-31'), overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 5, nodeName: '审批手续', plannedStart: new Date('2026-01-01'), plannedEnd: new Date('2026-01-15'), actualComplete: new Date('2026-01-15'), overdueDays: 0, tab: '前期', group: '项目端' },
      { id: 6, nodeName: '建设', plannedStart: new Date('2026-01-16'), plannedEnd: new Date('2026-03-15'), actualComplete: null, overdueDays: 0, tab: '建设期', group: '项目端' },
    ],
    createdAt: new Date('2025-11-01'),
  },
];

export const defaultNodes = [
  '前期开发', '立项', '投决', '合同签署', '审批手续', '建设', '运营', '交割', '消缺', '终止', '退出'
];